// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgenmodel

import (
	"time"
)

const TableNameSemanticRecord = "semantic_records"

// SemanticRecord mapped from table <semantic_records>
type SemanticRecord struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	NumberValue      int64     `gorm:"column:number_value;not null" json:"number_value"`
	DecimalValue     float64   `gorm:"column:decimal_value;not null" json:"decimal_value"`
	TextValue        string    `gorm:"column:text_value;not null" json:"text_value"`
	BoolValue        bool      `gorm:"column:bool_value;not null" json:"bool_value"`
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`
	NullableNumber   *int64    `gorm:"column:nullable_number" json:"nullable_number"`
	NullableText     *string   `gorm:"column:nullable_text" json:"nullable_text"`
	EqualityOnlyText string    `gorm:"column:equality_only_text;not null" json:"equality_only_text"`
}

// TableName SemanticRecord's table name
func (*SemanticRecord) TableName() string {
	return TableNameSemanticRecord
}
