// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgenquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/imbrooklyn/weave-integration-testbed/internal/gormgenmodel"
)

func newSemanticRecord(db *gorm.DB, opts ...gen.DOOption) semanticRecord {
	_semanticRecord := semanticRecord{}

	_semanticRecord.semanticRecordDo.UseDB(db, opts...)
	_semanticRecord.semanticRecordDo.UseModel(&gormgenmodel.SemanticRecord{})

	tableName := _semanticRecord.semanticRecordDo.TableName()
	_semanticRecord.ALL = field.NewAsterisk(tableName)
	_semanticRecord.ID = field.NewString(tableName, "id")
	_semanticRecord.NumberValue = field.NewInt64(tableName, "number_value")
	_semanticRecord.DecimalValue = field.NewFloat64(tableName, "decimal_value")
	_semanticRecord.TextValue = field.NewString(tableName, "text_value")
	_semanticRecord.BoolValue = field.NewBool(tableName, "bool_value")
	_semanticRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_semanticRecord.NullableNumber = field.NewInt64(tableName, "nullable_number")
	_semanticRecord.NullableText = field.NewString(tableName, "nullable_text")
	_semanticRecord.EqualityOnlyText = field.NewString(tableName, "equality_only_text")

	_semanticRecord.fillFieldMap()

	return _semanticRecord
}

type semanticRecord struct {
	semanticRecordDo

	ALL              field.Asterisk
	ID               field.String
	NumberValue      field.Int64
	DecimalValue     field.Float64
	TextValue        field.String
	BoolValue        field.Bool
	CreatedAt        field.Time
	NullableNumber   field.Int64
	NullableText     field.String
	EqualityOnlyText field.String

	fieldMap map[string]field.Expr
}

func (s semanticRecord) Table(newTableName string) *semanticRecord {
	s.semanticRecordDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s semanticRecord) As(alias string) *semanticRecord {
	s.semanticRecordDo.DO = *(s.semanticRecordDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *semanticRecord) updateTableName(table string) *semanticRecord {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.NumberValue = field.NewInt64(table, "number_value")
	s.DecimalValue = field.NewFloat64(table, "decimal_value")
	s.TextValue = field.NewString(table, "text_value")
	s.BoolValue = field.NewBool(table, "bool_value")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.NullableNumber = field.NewInt64(table, "nullable_number")
	s.NullableText = field.NewString(table, "nullable_text")
	s.EqualityOnlyText = field.NewString(table, "equality_only_text")

	s.fillFieldMap()

	return s
}

func (s *semanticRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *semanticRecord) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["number_value"] = s.NumberValue
	s.fieldMap["decimal_value"] = s.DecimalValue
	s.fieldMap["text_value"] = s.TextValue
	s.fieldMap["bool_value"] = s.BoolValue
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["nullable_number"] = s.NullableNumber
	s.fieldMap["nullable_text"] = s.NullableText
	s.fieldMap["equality_only_text"] = s.EqualityOnlyText
}

func (s semanticRecord) clone(db *gorm.DB) semanticRecord {
	s.semanticRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s semanticRecord) replaceDB(db *gorm.DB) semanticRecord {
	s.semanticRecordDo.ReplaceDB(db)
	return s
}

type semanticRecordDo struct{ gen.DO }

type ISemanticRecordDo interface {
	gen.SubQuery
	Debug() ISemanticRecordDo
	WithContext(ctx context.Context) ISemanticRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISemanticRecordDo
	WriteDB() ISemanticRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISemanticRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISemanticRecordDo
	Not(conds ...gen.Condition) ISemanticRecordDo
	Or(conds ...gen.Condition) ISemanticRecordDo
	Select(conds ...field.Expr) ISemanticRecordDo
	Where(conds ...gen.Condition) ISemanticRecordDo
	Order(conds ...field.Expr) ISemanticRecordDo
	Distinct(cols ...field.Expr) ISemanticRecordDo
	Omit(cols ...field.Expr) ISemanticRecordDo
	Join(table schema.Tabler, on ...field.Expr) ISemanticRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISemanticRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISemanticRecordDo
	Group(cols ...field.Expr) ISemanticRecordDo
	Having(conds ...gen.Condition) ISemanticRecordDo
	Limit(limit int) ISemanticRecordDo
	Offset(offset int) ISemanticRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISemanticRecordDo
	Unscoped() ISemanticRecordDo
	Create(values ...*gormgenmodel.SemanticRecord) error
	CreateInBatches(values []*gormgenmodel.SemanticRecord, batchSize int) error
	Save(values ...*gormgenmodel.SemanticRecord) error
	First() (*gormgenmodel.SemanticRecord, error)
	Take() (*gormgenmodel.SemanticRecord, error)
	Last() (*gormgenmodel.SemanticRecord, error)
	Find() ([]*gormgenmodel.SemanticRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gormgenmodel.SemanticRecord, err error)
	FindInBatches(result *[]*gormgenmodel.SemanticRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*gormgenmodel.SemanticRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISemanticRecordDo
	Assign(attrs ...field.AssignExpr) ISemanticRecordDo
	Joins(fields ...field.RelationField) ISemanticRecordDo
	Preload(fields ...field.RelationField) ISemanticRecordDo
	FirstOrInit() (*gormgenmodel.SemanticRecord, error)
	FirstOrCreate() (*gormgenmodel.SemanticRecord, error)
	FindByPage(offset int, limit int) (result []*gormgenmodel.SemanticRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISemanticRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s semanticRecordDo) Debug() ISemanticRecordDo {
	return s.withDO(s.DO.Debug())
}

func (s semanticRecordDo) WithContext(ctx context.Context) ISemanticRecordDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s semanticRecordDo) ReadDB() ISemanticRecordDo {
	return s.Clauses(dbresolver.Read)
}

func (s semanticRecordDo) WriteDB() ISemanticRecordDo {
	return s.Clauses(dbresolver.Write)
}

func (s semanticRecordDo) Session(config *gorm.Session) ISemanticRecordDo {
	return s.withDO(s.DO.Session(config))
}

func (s semanticRecordDo) Clauses(conds ...clause.Expression) ISemanticRecordDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s semanticRecordDo) Returning(value interface{}, columns ...string) ISemanticRecordDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s semanticRecordDo) Not(conds ...gen.Condition) ISemanticRecordDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s semanticRecordDo) Or(conds ...gen.Condition) ISemanticRecordDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s semanticRecordDo) Select(conds ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s semanticRecordDo) Where(conds ...gen.Condition) ISemanticRecordDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s semanticRecordDo) Order(conds ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s semanticRecordDo) Distinct(cols ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s semanticRecordDo) Omit(cols ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s semanticRecordDo) Join(table schema.Tabler, on ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s semanticRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s semanticRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s semanticRecordDo) Group(cols ...field.Expr) ISemanticRecordDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s semanticRecordDo) Having(conds ...gen.Condition) ISemanticRecordDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s semanticRecordDo) Limit(limit int) ISemanticRecordDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s semanticRecordDo) Offset(offset int) ISemanticRecordDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s semanticRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISemanticRecordDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s semanticRecordDo) Unscoped() ISemanticRecordDo {
	return s.withDO(s.DO.Unscoped())
}

func (s semanticRecordDo) Create(values ...*gormgenmodel.SemanticRecord) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s semanticRecordDo) CreateInBatches(values []*gormgenmodel.SemanticRecord, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s semanticRecordDo) Save(values ...*gormgenmodel.SemanticRecord) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s semanticRecordDo) First() (*gormgenmodel.SemanticRecord, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gormgenmodel.SemanticRecord), nil
	}
}

func (s semanticRecordDo) Take() (*gormgenmodel.SemanticRecord, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gormgenmodel.SemanticRecord), nil
	}
}

func (s semanticRecordDo) Last() (*gormgenmodel.SemanticRecord, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gormgenmodel.SemanticRecord), nil
	}
}

func (s semanticRecordDo) Find() ([]*gormgenmodel.SemanticRecord, error) {
	result, err := s.DO.Find()
	return result.([]*gormgenmodel.SemanticRecord), err
}

func (s semanticRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gormgenmodel.SemanticRecord, err error) {
	buf := make([]*gormgenmodel.SemanticRecord, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s semanticRecordDo) FindInBatches(result *[]*gormgenmodel.SemanticRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s semanticRecordDo) Attrs(attrs ...field.AssignExpr) ISemanticRecordDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s semanticRecordDo) Assign(attrs ...field.AssignExpr) ISemanticRecordDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s semanticRecordDo) Joins(fields ...field.RelationField) ISemanticRecordDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s semanticRecordDo) Preload(fields ...field.RelationField) ISemanticRecordDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s semanticRecordDo) FirstOrInit() (*gormgenmodel.SemanticRecord, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gormgenmodel.SemanticRecord), nil
	}
}

func (s semanticRecordDo) FirstOrCreate() (*gormgenmodel.SemanticRecord, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gormgenmodel.SemanticRecord), nil
	}
}

func (s semanticRecordDo) FindByPage(offset int, limit int) (result []*gormgenmodel.SemanticRecord, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s semanticRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s semanticRecordDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s semanticRecordDo) Delete(models ...*gormgenmodel.SemanticRecord) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *semanticRecordDo) withDO(do gen.Dao) *semanticRecordDo {
	s.DO = *do.(*gen.DO)
	return s
}
